[package]
name = "cre8t1ve/opencloud"
description = "Roblox's OpenCloud module"
version = "0.29737691850.0"
license = "MIT"
authors = ["Roblox"]
realm = "server"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://create.roblox.com/store/asset/16584168800/Open-Cloud"
repository = "https://github.com/cre8t1ve/opencloud"
